[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\r/home/gabrieu)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x84\0\0\0\x6\0\0\x4y\0\0\x4/\0\0\x1\x84\0\0\0\x6\0\0\x4y\0\0\x4/\0\0\0\0\0\0\0\0\a\x80\0\0\x1\x84\0\0\0\x6\0\0\x4y\0\0\x4/)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(758 992)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/gabrieu/Downloads/Design%20sem%20nome%282%29.png, file:///home/gabrieu/Downloads/Design%20sem%20nome%281%29.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-11_13-56-05.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-13_14-51-15.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-11_13-50-53.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-10_22-08-13.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-10_20-30-23.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-15_15-49-40.png, file:///home/gabrieu/Images/Screenshots/screenshot_2025-02-18_08-58-20.png, file:///home/gabrieu/.config/hypr/backgrounds/awesome.png, file:///home/gabrieu/.config/hypr/backgrounds/ALL.png, file:///home/gabrieu/.config/hypr/backgrounds/future-town.jpg, file:///home/gabrieu/.config/hypr/backgrounds/ArchGruvbox.png, file:///home/gabrieu/.config/hypr/backgrounds/Tranquility.png, file:///home/gabrieu/.config/hypr/backgrounds/wallhaven.jpg
times=0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, -1
