# Gruvbox Colors
$background = rgba(40, 40, 40, 1.0)         #282828
$foreground = rgba(235, 219, 178, 1)        #ebdbb2
$accent     = rgba(215, 153, 33, 1.0)
$input_bg   = rgba(40, 40, 40, 0.3)
$input_fg   = rgba(235, 219, 178, 0.8)
$input_border = rgba(168, 153, 132, 0.6)

# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 4
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    color = $background
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.4
    dots_center = true
    outer_color = $input_border
    inner_color = $input_bg
    font_color = $input_fg
    fade_on_empty = false
    rounding = -1
    check_color = $accent
    placeholder_text = <i><span foreground="##ebdbb2">Input Password...</span></i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] date +"%A, %B %d"
  color = $foreground
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] date +"%-H:%M"
  color = $foreground
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}

# CURRENT SONG
label {
    monitor = 
    text = cmd[update:1000] $HOME/.scripts/whatsong.sh 
    color = $accent
    font_family = JetBrains Mono Nerd Extrabold
    font_size = 12
    position = 0, 50
    halign = center
    valign = bottom
}
